### ISSUE TITLE
Issue with the spelling of a French town - La Queue-lez-Yvelines

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data-admin-fr#59]
As originally reported in https://github.com/pelias/pelias/issues/918, the user reported that the locals spell the place name using the `lez` form in place of `les`.

I did a little digging and wasn't able to confirm that this is an official name change (although I could be wrong or it may be very recent).

Either way, I believe this is a valid alias considering the town hall uses the 'z' version:
http://www.la-queue-lez-yvelines.fr/

- https://spelunker.whosonfirst.org/id/101828071/
- https://www.insee.fr/fr/metadonnees/cog/commune/COM78513-la-queue-les-yvelines

**Comment by stepps00** [comment]
Thanks @missinglink 

According to Wikipedia, the "official" spelling (what WOF would use in `preferred` name properties) is "La Queue-les-Yvelines": https://en.wikipedia.org/wiki/La_Queue-les-Yvelines

WOF does maintain the "La Queue-lez-Yvelines" name as a French variant.. I think we're good here, but let me know if there is something I'm missing. Happy to add additional variants where needed.

**Comment by missinglink** [comment]
Agh you're right sorry I missed that it's in the `variant` names.

We recently decided to [stop importing variant](https://github.com/pelias/whosonfirst/pull/529) names because they contain a lot of colloquialisms (eg. `Thebigapple` `Bigapple` for NYC, `Fresco` for SF etc) which increased recall but at the expense of causing precision issues in Pelias, I also noticed [this comment](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/104#discussion_r708507423) and felt like we didn't want to bring in spelling mistakes from the `variant` field due to lifecycle rules.

In this case the `variant` is a legitimate alias we'd like to import so I'm not sure how best to qualify which names from those fields are desirable and which aren't.

**Comment by stepps00** [comment]
Yeah, for the most part, the variant names are a "grab bag" of names that are sometimes inclusive of colloquial terms. Longer term, we can discuss maintaining the colloquial terms in just the `_x_colloquial` properties.. but I think in this case there is no data work to do, so I'll close.
